# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 107befcd4600c5700064f0ff94dbbf8932d03333e271b678034556b94bfb47e0e9997cd551f04f560c0930cff19771732d6c3e7238a07625852d407a6259ae69

test:
  secret_key_base: eebbd2aa5d17035a3132b12eaf336724e404a08944969695fac691fc6b36d6ca1ea3e432a519ce8ceca644ff02ed79ad956bef1140660cb245b12532a16fee88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
